# Makefile.in generated automatically by automake 1.5 from Makefile.am.
# Generated automatically from Makefile.in by config.pl.
# KDE tags expanded automatically by am_edit - $Revision: 1.6 $ 

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



####### kdevelop will overwrite this part!!! (begin)##########

SHELL = /bin/sh

srcdir = .
top_srcdir = ..
VPATH = .
prefix = /usr/local/kde
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/rohc-gui
pkglibdir = $(libdir)/rohc-gui
pkgincludedir = $(includedir)/rohc-gui
top_builddir = ..

ACLOCAL = ${SHELL} /home/erik/final_co/rohc/gui/admin/missing --run aclocal
AUTOCONF = ${SHELL} /home/erik/final_co/rohc/gui/admin/missing --run autoconf
AUTOMAKE = ${SHELL} /home/erik/final_co/rohc/gui/admin/missing --run automake
AUTOHEADER = ${SHELL} /home/erik/final_co/rohc/gui/admin/missing --run autoheader

INSTALL = /usr/bin/install -c -p
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,^,i386-linux-,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i386-linux
build_triplet = i386-pc-linux-gnu
host_alias = i386-linux
host_triplet = i386-pc-linux-gnu
target_alias = i386-linux
target_triplet = i386-pc-linux-gnu
AMTAR = ${SHELL} /home/erik/final_co/rohc/gui/admin/missing --run tar
ARTSCCONFIG = /usr/bin/artsc-config
AS = @AS@
AUTODIRS = 
AWK = gawk
CC = gcc
CONF_FILES =  $(top_srcdir)/./admin/configure.in.min $(top_srcdir)/configure.in.in
CPP = cpp
CXX = g++
CXXCPP = g++ -E
DCOPIDL = /usr/bin/dcopidl
DCOPIDL2CPP = /usr/bin/dcopidl2cpp
DCOP_DEPENDENCIES = $(DCOPIDL)
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
DOXYGEN = @DOXYGEN@
DOXYGEN_PROJECT_NAME = @DOXYGEN_PROJECT_NAME@
DOXYGEN_PROJECT_NUMBER = @DOXYGEN_PROJECT_NUMBER@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
ECHO = echo
EXEEXT = 
FRAMEWORK_COREAUDIO = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
JAR = @JAR@
JAVAC = @JAVAC@
JAVAH = @JAVAH@
JVMLIBS = @JVMLIBS@
KDECONFIG = /usr/bin/kde-config
KDE_EXTRA_RPATH = 
KDE_HAS_DOXYGEN = @KDE_HAS_DOXYGEN@
KDE_HAVE_DOT = @KDE_HAVE_DOT@
KDE_INCLUDES = -I/usr/include/kde
KDE_LDFLAGS = -L/usr/lib
KDE_MT_LDFLAGS = 
KDE_MT_LIBS = -lpthread
KDE_PLUGIN = -avoid-version -module -no-undefined $(KDE_RPATH) $(KDE_MT_LDFLAGS)
KDE_RPATH = -R $(kde_libraries) -R $(qt_libraries) -R $(x_libraries)
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KDE_XSL_STYLESHEET = /usr/share/apps/ksgmltools2/customization/kde-chunk.xsl
LEX = @LEX@
LEXLIB = @LEXLIB@
LIBBZ2 = @LIBBZ2@
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBGEN = @LIBGEN@
LIBJPEG = -ljpeg
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBPNG = -lpng -lz -lm
LIBPTHREAD = -lpthread
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBRESOLV = -lresolv
LIBSHADOW = @LIBSHADOW@
LIBSM = -lSM -lICE
LIBSOCKET = 
LIBSSL = @LIBSSL@
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool --silent
LIBUCB = 
LIBUTIL = -lutil
LIBXINERAMA = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KABC = -lkabc
LIB_KDECORE = -lkdecore
LIB_KDEPRINT = -lkdeprint
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkio
LIB_KFM = 
LIB_KHTML = -lkhtml
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = -lkio
LIB_KPARTS = -lkparts
LIB_KSPELL = -lkspell
LIB_KSYCOCA = -lkio
LIB_POLL = 
LIB_QPE = 
LIB_QT = -lqt-mt  $(LIBPNG) -lXext $(LIB_X11) $(LIBSM) -lpthread
LIB_QTOPIA = @LIB_QTOPIA@
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LIB_XEXT = -lXext
LN_S = ln -s
MCOPIDL = /usr/bin/mcopidl
MEINPROC = /usr/bin/meinproc
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /usr/lib/qt-3.1/bin/moc
MSGFMT = /usr/bin/msgfmt
NOOPT_CFLAGS = -O0
NOOPT_CXXFLAGS = -O0
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = rohc-gui
PAMLIBS = @PAMLIBS@
PASSWDLIBS = @PASSWDLIBS@
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
PYTHONMODDIR = @PYTHONMODDIR@
QTDOCDIR = @QTDOCDIR@
QTE_NORTTI = 
QTOPIA_INCLUDES = @QTOPIA_INCLUDES@
QT_INCLUDES = -I/usr/lib/qt-3.1/include
QT_LDFLAGS = -L/usr/lib/qt-3.1/lib
RANLIB = ranlib
RC = @RC@
REPO = -frepo
SETUIDFLAGS = @SETUIDFLAGS@
SSL_INCLUDES = @SSL_INCLUDES@
SSL_LDFLAGS = @SSL_LDFLAGS@
STRIP = strip
TOPSUBDIRS =  doc po small
UIC = /usr/lib/qt-3.1/bin/uic -L $(kde_widgetdir) -nounload
UIC_TR = tr2i18n
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = -fexceptions
USE_RTTI = 
USE_THREADS = 
VERSION = 0.1
WOVERLOADED_VIRTUAL = 
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = 
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
X_PRE_LIBS = 
all_includes = -I/usr/include/kde -I/usr/lib/qt-3.1/include -I/usr/X11R6/include 
all_libraries = -L/usr/X11R6/lib -L/usr/lib/qt-3.1/lib -L/usr/lib 
am__include = include
am__quote = 
idldir = @idldir@
install_sh = /home/erik/final_co/rohc/gui/admin/install-sh
jni_includes = @jni_includes@
kde_appsdir = ${prefix}/share/applnk
kde_bindir = ${exec_prefix}/bin
kde_confdir = ${prefix}/share/config
kde_datadir = ${prefix}/share/apps
kde_htmldir = ${prefix}/share/doc/HTML
kde_icondir = ${prefix}/share/icons
kde_includes = /usr/include/kde
kde_libraries = /usr/lib
kde_libs_htmldir = /usr/share/doc/HTML
kde_libs_prefix = /usr
kde_locale = ${prefix}/share/locale
kde_mimedir = ${prefix}/share/mimelnk
kde_moduledir = ${libdir}/kde3
kde_qtver = 3
kde_servicesdir = ${prefix}/share/services
kde_servicetypesdir = ${prefix}/share/servicetypes
kde_sounddir = ${prefix}/share/sounds
kde_styledir = ${libdir}/kde3/plugins/styles
kde_templatesdir = ${prefix}/share/templates
kde_wallpaperdir = ${prefix}/share/wallpapers
kde_widgetdir = /usr/lib/kde3/plugins/designer
micodir = @micodir@
qt_includes = /usr/lib/qt-3.1/include
qt_libraries = /usr/lib/qt-3.1/lib
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib

bin_PROGRAMS = small

#>- small_SOURCES = StyleSettings.ui ColorPicker.cc StyleEngine.cc SignalPlotter.cc objhandler.cpp ROHCProfileTable.cpp ROHCInstanceTable.cpp ROHCContextTable.cpp proccom.cpp parser.cpp saken.ui small.cpp main.cpp 
#>+ 1
small_SOURCES= ColorPicker.cc StyleEngine.cc SignalPlotter.cc objhandler.cpp ROHCProfileTable.cpp ROHCInstanceTable.cpp ROHCContextTable.cpp proccom.cpp parser.cpp  small.cpp main.cpp  StyleSettings.cc saken.cc
small_LDADD = $(LIB_KDEUI) $(LIB_KDECORE) $(LIB_QT) $(LIBSOCKET)

EXTRA_DIST = main.cpp small.cpp small.h small.desktop lo32-app-small.png lo16-app-small.png saken.ui objhandler.h parser.cpp parser.h proccom.cpp proccom.h ROHCContextTable.cpp ROHCContextTable.h ROHCInstanceTable.cpp ROHCInstanceTable.h ROHCProfileTable.cpp ROHCProfileTable.h objhandler.cpp proctest SignalPlotter.cc SignalPlotter.h StyleEngine.cc StyleEngine.h ColorPicker.cc ColorPicker.h StyleSettings.ui 

####### kdevelop will overwrite this part!!! (end)############
# These paths are KDE specific. Use them:
# kde_appsdir         Where your application's menu entry (.desktop) should go to.
# kde_icondir         Where your icon should go to - better use KDE_ICON.
# kde_sounddir        Where your sounds should go to.
# kde_htmldir         Where your docs should go to. (contains lang subdirs)
# kde_datadir         Where you install application data. (Use a subdir)
# kde_locale          Where translation files should go to. (contains lang subdirs)
# kde_cgidir          Where cgi-bin executables should go to.
# kde_confdir         Where config files should go to (system-wide ones with default values).
# kde_mimedir         Where mimetypes .desktop files should go to.
# kde_servicesdir     Where services .desktop files should go to.
# kde_servicetypesdir Where servicetypes .desktop files should go to.
# kde_toolbardir      Where general toolbar icons should go to (deprecated, use KDE_ICON).
# kde_wallpaperdir    Where general wallpapers should go to.
# kde_templatesdir    Where templates for the "New" menu (Konqueror/KDesktop) should go to.
# kde_bindir          Where executables should go to. Use bin_PROGRAMS or bin_SCRIPTS.
# kde_libdir          Where shared libraries should go to. Use lib_LTLIBRARIES.
# kde_moduledir       Where modules (e.g. parts) should go to. Use kde_module_LTLIBRARIES.
# kde_styledir        Where Qt/KDE widget styles should go to (new in KDE 3).
# kde_designerdir     Where Qt Designer plugins should go to (new in KDE 3).

# set the include path for X, qt and KDE
INCLUDES = $(all_includes)

#>- METASOURCES = AUTO

# the library search path. 
small_LDFLAGS = $(all_libraries) $(KDE_RPATH)
subdir = small
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
bin_PROGRAMS = small$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)

am_small_OBJECTS = ColorPicker.$(OBJEXT) StyleEngine.$(OBJEXT) \
	SignalPlotter.$(OBJEXT) objhandler.$(OBJEXT) \
	ROHCProfileTable.$(OBJEXT) ROHCInstanceTable.$(OBJEXT) \
	ROHCContextTable.$(OBJEXT) proccom.$(OBJEXT) parser.$(OBJEXT) \
	small.$(OBJEXT) main.$(OBJEXT)
#>- small_OBJECTS = $(am_small_OBJECTS)
#>+ 9
small_final_OBJECTS = small.all_cc.o small.all_cpp.o 
small_nofinal_OBJECTS = ColorPicker.$(OBJEXT) StyleEngine.$(OBJEXT) \
	SignalPlotter.$(OBJEXT) objhandler.$(OBJEXT) \
	ROHCProfileTable.$(OBJEXT) ROHCInstanceTable.$(OBJEXT) \
	ROHCContextTable.$(OBJEXT) proccom.$(OBJEXT) parser.$(OBJEXT) \
	small.$(OBJEXT) main.$(OBJEXT) StyleSettings.$(OBJEXT) saken.$(OBJEXT)\
small.moc.o 
small_OBJECTS = $(small_nofinal_OBJECTS)
#small_OBJECTS = $(small_final_OBJECTS)
small_DEPENDENCIES =

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
CPPFLAGS =  -DQT_THREAD_SUPPORT  -D_REENTRANT
LDFLAGS = 
LIBS = 
depcomp = $(SHELL) $(top_srcdir)/admin/depcomp
#>- DEP_FILES = $(DEPDIR)/ColorPicker.Po \
#>- 	$(DEPDIR)/ROHCContextTable.Po \
#>- 	$(DEPDIR)/ROHCInstanceTable.Po \
#>- 	$(DEPDIR)/ROHCProfileTable.Po \
#>- 	$(DEPDIR)/SignalPlotter.Po $(DEPDIR)/StyleEngine.Po \
#>- 	$(DEPDIR)/main.Po $(DEPDIR)/objhandler.Po \
#>- 	$(DEPDIR)/parser.Po $(DEPDIR)/proccom.Po \
#>- 	$(DEPDIR)/small.Po
#>+ 17
#DEP_FILES =  $(DEPDIR)/StyleSettings.P $(DEPDIR)/saken.P $(DEPDIR)/small.moc.P  $(DEPDIR)/small.all_cc.P $(DEPDIR)/small.all_cpp.P  $(DEPDIR)/ColorPicker.Po \
#		$(DEPDIR)/ROHCContextTable.Po \
#		$(DEPDIR)/ROHCInstanceTable.Po \
#		$(DEPDIR)/ROHCProfileTable.Po \
#		$(DEPDIR)/SignalPlotter.Po $(DEPDIR)/StyleEngine.Po \
#		$(DEPDIR)/main.Po $(DEPDIR)/objhandler.Po \
#		$(DEPDIR)/parser.Po $(DEPDIR)/proccom.Po \
#		$(DEPDIR)/small.Po
DEP_FILES =  $(DEPDIR)/StyleSettings.P $(DEPDIR)/saken.P $(DEPDIR)/small.moc.P  $(DEPDIR)/ColorPicker.Po \
		$(DEPDIR)/ROHCContextTable.Po \
		$(DEPDIR)/ROHCInstanceTable.Po \
		$(DEPDIR)/ROHCProfileTable.Po \
		$(DEPDIR)/SignalPlotter.Po $(DEPDIR)/StyleEngine.Po \
		$(DEPDIR)/main.Po $(DEPDIR)/objhandler.Po \
		$(DEPDIR)/parser.Po $(DEPDIR)/proccom.Po \
		$(DEPDIR)/small.Po

#>- CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
#>- 	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 2
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
#>- LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) \
#>- 	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
#>- 	$(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 3
LTCXXCOMPILE = $(LIBTOOL) --mode=compile --tag=CXX $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
CXXLD = $(CXX)
#>- CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
#>- 	$(AM_LDFLAGS) $(LDFLAGS) -o $@
#>+ 2
CXXLINK = $(LIBTOOL) --mode=link --tag=CXX $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
CXXFLAGS = -Wnon-virtual-dtor -Wno-long-long -Wundef -Wall -pedantic -W -Wpointer-arith -Wmissing-prototypes -Wwrite-strings -ansi -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -Wcast-align -Wconversion -O2 -O0 -g3 -Wall -fno-exceptions -fno-check-new
CFLAGS = -ansi -W -Wall -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -O2  
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) \
	$(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
DIST_SOURCES = $(small_SOURCES)
DIST_COMMON = Makefile.am Makefile.in
SOURCES = $(small_SOURCES)

#>- all: all-am
#>+ 1
all: docs-am  all-am

.SUFFIXES:
.SUFFIXES: .cc .cpp .lo .o .obj

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
#>- 	cd $(top_srcdir) && \
#>- 	  $(AUTOMAKE) --gnu  small/Makefile
#>+ 3
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  small/Makefile
	cd $(top_srcdir) && perl admin/am_edit small/Makefile.in
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	     || test -f $$p1 \
	  ; then \
	    f=`echo $$p1|sed '$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f"; \
	   $(INSTALL_PROGRAM_ENV) $(LIBTOOL) --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
small$(EXEEXT): $(small_OBJECTS) $(small_DEPENDENCIES) 
	@rm -f small$(EXEEXT)
	$(CXXLINK) $(small_LDFLAGS) $(small_OBJECTS) $(small_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/ColorPicker.Po
include $(DEPDIR)/ROHCContextTable.Po
include $(DEPDIR)/ROHCInstanceTable.Po
include $(DEPDIR)/ROHCProfileTable.Po
include $(DEPDIR)/SignalPlotter.Po
include $(DEPDIR)/StyleEngine.Po
include $(DEPDIR)/main.Po
include $(DEPDIR)/objhandler.Po
include $(DEPDIR)/parser.Po
include $(DEPDIR)/proccom.Po
include $(DEPDIR)/small.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.cc.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<

.cc.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `cygpath -w $<`

.cc.lo:
	source='$<' object='$@' libtool=yes \
	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' \
	$(CXXDEPMODE) $(depcomp) \
	$(LTCXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<
CXXDEPMODE = depmode=gcc3

.cpp.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<

.cpp.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `cygpath -w $<`

.cpp.lo:
	source='$<' object='$@' libtool=yes \
	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' \
	$(CXXDEPMODE) $(depcomp) \
	$(LTCXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

#>- DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
#>+ 4
KDE_DIST=kalle.grek saken.h saken.cpp olle.grek small StyleSettings.h procsyntax.txt senapsgas.txt testfil.txt proctest.txt 

DISTFILES= $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST) $(KDE_DIST)


top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(bindir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

#>- clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am
#>+ 1
clean-am: clean-metasources clean-ui clean-final  clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am: install-data-local

install-exec-am: install-binPROGRAMS

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

uninstall-am: uninstall-binPROGRAMS uninstall-info-am uninstall-local

.PHONY: GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic clean-libtool distclean distclean-compile \
	distclean-depend distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am info info-am install \
	install-am install-binPROGRAMS install-data install-data-am \
	install-data-local install-exec install-exec-am install-info \
	install-info-am install-man install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool tags uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-info-am \
	uninstall-local


install-data-local:
#>- 	$(mkinstalldirs) $(kde_appsdir)/Applications/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)$(kde_appsdir)/Applications/
#>- 	$(INSTALL_DATA) $(srcdir)/small.desktop $(kde_appsdir)/Applications/small.desktop
#>+ 1
	$(INSTALL_DATA) $(srcdir)/small.desktop $(DESTDIR)$(kde_appsdir)/Applications/small.desktop
#>- 	$(mkinstalldirs) $(kde_icondir)/locolor/32x32/apps/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)$(kde_icondir)/locolor/32x32/apps/
#>- 	$(INSTALL_DATA) $(srcdir)/lo32-app-small.png $(kde_icondir)/locolor/32x32/apps/small.png
#>+ 1
	$(INSTALL_DATA) $(srcdir)/lo32-app-small.png $(DESTDIR)$(kde_icondir)/locolor/32x32/apps/small.png
#>- 	$(mkinstalldirs) $(kde_icondir)/locolor/16x16/apps/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)$(kde_icondir)/locolor/16x16/apps/
#>- 	$(INSTALL_DATA) $(srcdir)/lo16-app-small.png $(kde_icondir)/locolor/16x16/apps/small.png
#>+ 1
	$(INSTALL_DATA) $(srcdir)/lo16-app-small.png $(DESTDIR)$(kde_icondir)/locolor/16x16/apps/small.png

uninstall-local:
#>- 	-rm -f $(kde_appsdir)/Applications/small.desktop
#>+ 1
	-rm -f $(DESTDIR)$(kde_appsdir)/Applications/small.desktop
#>- 	-rm -f $(kde_icondir)/locolor/32x32/apps/small.png
#>+ 1
	-rm -f $(DESTDIR)$(kde_icondir)/locolor/32x32/apps/small.png
#>- 	-rm -f $(kde_icondir)/locolor/16x16/apps/small.png
#>+ 1
	-rm -f $(DESTDIR)$(kde_icondir)/locolor/16x16/apps/small.png

# Uncomment the following two lines if you add a ui.rc file for your application to make use of
# KDEs XML GUI builing
#rcdir = $(kde_datadir)/small
#rc_DATA = smallui.rc

#WARNING: if you use a ui.rc file above, use:

# messages: rc.cpp

# instead of 

# messages:

messages: 
	LIST=`find . -name \*.h -o -name \*.hh -o -name \*.H -o -name \*.hxx -o -name \*.hpp -o -name \*.cpp -o -name \*.cc -o -name \*.cxx -o -name \*.ecpp -o -name \*.C`; \
	if test -n "$$LIST"; then \
	 $(XGETTEXT) $$LIST -o $(podir)/small.pot; \
	fi
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 27
StyleSettings.cc: $(srcdir)/StyleSettings.ui StyleSettings.h StyleSettings.moc
	rm -f StyleSettings.cc
	echo '#include <klocale.h>' > StyleSettings.cc
	$(UIC) -tr ${UIC_TR} -i StyleSettings.h $(srcdir)/StyleSettings.ui > StyleSettings.cc.temp ; ret=$$?; \
	sed -e "s,${UIC_TR}( \"\" ),QString::null,g" StyleSettings.cc.temp | sed -e "s,${UIC_TR}( \"\"\, \"\" ),QString::null,g" | sed -e "s,image\([0-9][0-9]*\)_data,img\1_StyleSettings,g" >> StyleSettings.cc ;\
	rm -f StyleSettings.cc.temp ;\
	if test "$$ret" = 0; then echo '#include "StyleSettings.moc"' >> StyleSettings.cc; else rm -f StyleSettings.cc ; exit $$ret ; fi

StyleSettings.h: $(srcdir)/StyleSettings.ui
	$(UIC) -o StyleSettings.h $(srcdir)/StyleSettings.ui

StyleSettings.moc: StyleSettings.h
	$(MOC) StyleSettings.h -o StyleSettings.moc
saken.cc: $(srcdir)/saken.ui saken.h saken.moc
	rm -f saken.cc
	echo '#include <klocale.h>' > saken.cc
	$(UIC) -tr ${UIC_TR} -i saken.h $(srcdir)/saken.ui > saken.cc.temp ; ret=$$?; \
	sed -e "s,${UIC_TR}( \"\" ),QString::null,g" saken.cc.temp | sed -e "s,${UIC_TR}( \"\"\, \"\" ),QString::null,g" | sed -e "s,image\([0-9][0-9]*\)_data,img\1_saken,g" >> saken.cc ;\
	rm -f saken.cc.temp ;\
	if test "$$ret" = 0; then echo '#include "saken.moc"' >> saken.cc; else rm -f saken.cc ; exit $$ret ; fi

saken.h: $(srcdir)/saken.ui
	$(UIC) -o saken.h $(srcdir)/saken.ui

saken.moc: saken.h
	$(MOC) saken.h -o saken.moc

#>+ 3
small.moc.cc: $(srcdir)/small.h
	$(MOC) $(srcdir)/small.h -o small.moc.cc

#>+ 3
ColorPicker.moc: $(srcdir)/ColorPicker.h
	$(MOC) $(srcdir)/ColorPicker.h -o ColorPicker.moc

#>+ 3
SignalPlotter.moc: $(srcdir)/SignalPlotter.h
	$(MOC) $(srcdir)/SignalPlotter.h -o SignalPlotter.moc

#>+ 3
StyleEngine.moc: $(srcdir)/StyleEngine.h
	$(MOC) $(srcdir)/StyleEngine.h -o StyleEngine.moc

#>+ 3
clean-metasources:
	-rm -f  small.moc.cc ColorPicker.moc SignalPlotter.moc StyleEngine.moc

#>+ 5
clean-ui:
	-rm -f \
	StyleSettings.cc StyleSettings.h StyleSettings.moc \
	saken.cc saken.h saken.moc 

#>+ 2
docs-am:

#>+ 6
force-reedit:
		cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  small/Makefile
	cd $(top_srcdir) && perl admin/am_edit small/Makefile.in


#>+ 11
small.all_cc.cc: $(srcdir)/Makefile.in $(srcdir)/ColorPicker.cc $(srcdir)/StyleEngine.cc $(srcdir)/SignalPlotter.cc $(srcdir)/StyleSettings.cc $(srcdir)/saken.cc $(srcdir)/small.moc.cc  ColorPicker.moc SignalPlotter.moc StyleEngine.moc
	@echo 'creating small.all_cc.cc ...'; \
	rm -f small.all_cc.files small.all_cc.final; \
	echo "#define KDE_USE_FINAL 1" >> small.all_cc.final; \
	for file in ColorPicker.cc StyleEngine.cc SignalPlotter.cc StyleSettings.cc saken.cc small.moc.cc ; do \
	  echo "#include \"$$file\"" >> small.all_cc.files; \
	  test ! -f $(srcdir)/$$file || egrep '^#pragma +implementation' $(srcdir)/$$file >> small.all_cc.final; \
	done; \
	cat small.all_cc.final small.all_cc.files > small.all_cc.cc; \
	rm -f small.all_cc.final small.all_cc.files

#>+ 11
small.all_cpp.cpp: $(srcdir)/Makefile.in $(srcdir)/objhandler.cpp $(srcdir)/ROHCProfileTable.cpp $(srcdir)/ROHCInstanceTable.cpp $(srcdir)/ROHCContextTable.cpp $(srcdir)/proccom.cpp $(srcdir)/parser.cpp $(srcdir)/small.cpp $(srcdir)/main.cpp  ColorPicker.moc SignalPlotter.moc StyleEngine.moc
	@echo 'creating small.all_cpp.cpp ...'; \
	rm -f small.all_cpp.files small.all_cpp.final; \
	echo "#define KDE_USE_FINAL 1" >> small.all_cpp.final; \
	for file in objhandler.cpp ROHCProfileTable.cpp ROHCInstanceTable.cpp ROHCContextTable.cpp proccom.cpp parser.cpp small.cpp main.cpp ; do \
	  echo "#include \"$$file\"" >> small.all_cpp.files; \
	  test ! -f $(srcdir)/$$file || egrep '^#pragma +implementation' $(srcdir)/$$file >> small.all_cpp.final; \
	done; \
	cat small.all_cpp.final small.all_cpp.files > small.all_cpp.cpp; \
	rm -f small.all_cpp.final small.all_cpp.files

#>+ 3
clean-final:
	-rm -f small.all_cc.cc small.all_cpp.cpp

#>+ 2
final:
	$(MAKE) small_OBJECTS="$(small_final_OBJECTS)" all-am
#>+ 2
final-install:
	$(MAKE) small_OBJECTS="$(small_final_OBJECTS)" install-am
#>+ 2
no-final:
	$(MAKE) small_OBJECTS="$(small_nofinal_OBJECTS)" all-am
#>+ 2
no-final-install:
	$(MAKE) small_OBJECTS="$(small_nofinal_OBJECTS)" install-am
#>+ 3
cvs-clean:
	$(MAKE) admindir=$(top_srcdir)/admin -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo

#>+ 18
$(srcdir)/ColorPicker.cc: StyleSettings.h saken.h 
$(srcdir)/small.cpp: StyleSettings.h saken.h 
$(srcdir)/main.cpp: StyleSettings.h saken.h 
StyleEngine.o: StyleEngine.moc 
$(srcdir)/ROHCContextTable.cpp: StyleSettings.h saken.h 
$(srcdir)/ROHCInstanceTable.cpp: StyleSettings.h saken.h 
$(srcdir)/StyleEngine.cc: StyleSettings.h saken.h 
SignalPlotter.lo: SignalPlotter.moc 
StyleEngine.lo: StyleEngine.moc 
$(srcdir)/parser.cpp: StyleSettings.h saken.h 
$(srcdir)/SignalPlotter.cc: StyleSettings.h saken.h 
ColorPicker.o: ColorPicker.moc 
$(srcdir)/objhandler.cpp: StyleSettings.h saken.h 
SignalPlotter.o: SignalPlotter.moc 
$(srcdir)/ROHCProfileTable.cpp: StyleSettings.h saken.h 
ColorPicker.lo: ColorPicker.moc 
$(srcdir)/proccom.cpp: StyleSettings.h saken.h 
